### ISSUE TITLE
order not confirmed in joomla

### ISSUE THREAD

**Issue by mridulcs2012** [craigchristenson/2CO_VirtueMart2#1]
hi 
i installed this plugin in my joomla site with virtuemart. After i complete a demo payment, i see payment successful but order created is not marked as "confirmed".
Is not that needed setting a approve url? i don't see it where??

**Comment by craigchristenson** [comment]
The approved URL is passed in automatically and will work as long as the domain you are testing from matches the domain registered to your 2Checkout account. This URL is generated on the fly so it will change with every sale. If you are having problems with your account, please contact 2Checkout tech support at techsupport@2co.com so they can help troubleshoot the issue. Or if you like you can always hit me up directly at my email (find it on my github profile) and I will be happy to help your troubleshoot and get you up and running.

Thanks
