### ISSUE TITLE
Major Security Issue on this plugin

### ISSUE THREAD

**Issue by colighto** [craigchristenson/2CO_VirtueMart2#2]
Your plugin has a major security issue during submission of payment, it can easily be hacked by any users nevertheless if they are aware of this, when submitting the payment online users can just press "ESC" key to stop the transmission temporarily and change the hidden parameters using some developer tools, example is chrome developer tools I can update the amount in any value I want and just click on the submit button that I can see on the window and it can be successfully submitted to 2checkout without any hassle, it was processed successfully by 2checkout and the order got confirmed on the backend, definitely it didn't returned me any security warnings about the hack. I'm not sure if your aware of this issue but I think it's the payoff of using this free plugin though but I think people who are having 2checkout for their website should avoid using this plugin due to the issue until it's been properly addressed. But great thanks to your plugin I have something to play with though hehehe I will just edit the codes from here ;)

Regards

**Comment by craigchristenson** [comment]
Yea it looks like the return method erroneously uses the returned total in the hash check rather than the total from VirtueMart, that is why you did not get a warning. I will get that addressed for you. Thanks for reporting.

**Comment by craigchristenson** [comment]
https://github.com/craigchristenson/2CO_VirtueMart2/commit/810415d50b7e29dae3bcacfef539d76cf9b1f687
Now order will remain in pending state if total does not match.
